### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by hobbyL** [yiwei1223/daily#1]
你好。
你的这个作品我done下来，环境都装好了之后，运行失败，报错
[tid:com.facebook.React.RCTExceptionsManagerQueue] Unhandled JS Exception: Application daily has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.
你有时间帮忙解决下吗？

**Comment by yiwei1223** [comment]
你好，你的bug反馈信息显示是注册daily根组件失败
你可以查看一下ios/daily/AppDelegate.m第45行代码是否为：moduleName:@"daily"（即：moduleName为daily,这个是在项目初始化时就已经初始化好了的）
而后index.ios.js注册根组件名称为daily,代码如下：
AppRegistry.registerComponent('daily', () => DailyEnter);
两者一定要一致，否则就会出现下面的bug：
 Application daily has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent

**Comment by hobbyL** [comment]
问题解决了，谢谢。
